#?? ????.
server :
  port: 9000
#port전에 두칸 띄기 필수, 9000d앞에 한칸 띄기 필수  

#spring에 데이터 소스에 관한 코드
#dependencies에 mariadb를 추가 하였기 때문에 이렇게 사용할 수 있다
#jdbc라는 프로토콜에 열결하겠다. mariadb에게 내가 사용하는 포트 번호로 , 데이터베이스 이름을 적어준다(demo)-> mysql에 demo라는 데이터베이스를 만들어 주어야 한다.
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: ysh
    password: ysh123
